version: '3.8'
services:
  bravo:
    container_name: bravo
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: config
      MONGO_INITDB_ROOT_PASSWORD: config
    ports:
      - '27017:27017'
    command: mongod --port 27017 --configsvr --replSet alertme_cfg --dbpath /data/configdb 
  ekko:
    container_name: ekko
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: moravia
      MONGO_INITDB_ROOT_PASSWORD: moravia
    ports:
      - '27019:27019'
    command: mongod --port 27019 --replSet alertme_moravia --shardsvr
  lima:
    container_name: lima
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cartaguito
      MONGO_INITDB_ROOT_PASSWORD: campeon
    ports:
      - '27021:27021'
    command: mongod --port 27021 --replSet repl_srvs
